In [2]:
import pandas as pd

In [3]:
dir_path = "/content/drive/MyDrive/추천시스템 입문반/data/ml-latest-small"
with_rating_file_path = dir_path + '/tourist_attraction_with_rating.csv'
excluded_file_path = dir_path + '/tourist_attraction_with_rating_removed.csv'
rating_file = pd.read_csv(with_rating_file_path)
excluded_file = pd.read_csv(excluded_file_path)

In [4]:
print(rating_file.shape)
print(excluded_file.shape)

(4270, 30)
(93, 30)

In [5]:
origin_file_path = dir_path + '/jeju_tourist_attractions.csv'
origin_file = pd.read_csv(origin_file_path)
origin_file.shape

(4363, 28)

In [6]:
rating_file.sample()

,Unnamed: 0,Unnamed: 0.1,alltag,contentsid,title,address,roadaddress,tag,introduction,latitude,...,region2cd.label,region2cd.refId,repPhoto.descseo,repPhoto.photoid.photoid,repPhoto.photoid.imgpath,repPhoto.photoid.thumbnailpath,region1cd,region2cd,repPhoto,인기점수
971,971,88,"자연,체험,꽃,스쿠버다이빙,섬속의섬,해변,경관/포토,부모,친구,커플,아이,맑음,여름...",CNTS_000000000021591,꽃길만 걸어요 <제주 여름꽃 여행>,제주특별자치도 제주시 구좌읍 종달리,제주특별자치도 제주시 구좌읍,"자연,체험,꽃,스쿠버다이빙,섬속의섬,해변,경관/포토,부모,친구,커플,아이,맑음,여름...",후덥지근한 제주의 여름. 한발짝만 나서도 지칠 것 같은 날씨에 머리 위로는 뜨거운 ...,33.484333,...,region>,region>,꽃길만 걸어요 <제주 여름꽃 여행>,11525.0,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,NaN,NaN,NaN,8853.0

In [7]:
rating_file.drop(['Unnamed: 0','Unnamed: 0.1','region1cd','region2cd','repPhoto'],axis=1,inplace=True)
rating_file.sample()

,alltag,contentsid,title,address,roadaddress,tag,introduction,latitude,longitude,postcode,...,region1cd.label,region1cd.refId,region2cd.value,region2cd.label,region2cd.refId,repPhoto.descseo,repPhoto.photoid.photoid,repPhoto.photoid.imgpath,repPhoto.photoid.thumbnailpath,인기점수
1730,"겨울, 스파,실내",CNTS_200000000010796,롯데호텔 브이스파,제주특별자치도 서귀포시 색달동 2812-4,"제주특별자치도 서귀포시 중문관광로72번길 35, lobby floor 8F","겨울,스파,체험,호텔,어트랙션",서귀포시 중문관광단지의 롯데호텔제주는 프리미엄급으로 잘 알려진 휴양시설. 이 곳 별...,33.248458,126.410549,NaN,...,서귀포시,region>region2,24.0,중문,region2>24,롯데호텔 브이스파,2.019023e+12,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,2481.0

In [8]:
rating_file.sample()

,alltag,contentsid,title,address,roadaddress,tag,introduction,latitude,longitude,postcode,...,region1cd.label,region1cd.refId,region2cd.value,region2cd.label,region2cd.refId,repPhoto.descseo,repPhoto.photoid.photoid,repPhoto.photoid.imgpath,repPhoto.photoid.thumbnailpath,인기점수
2897,"의료관광, 병원, 웰니스, 헬스케어",CNTS_200000000009479,썬플라워의원,제주특별자치도 제주시 한림읍 협재리 2838,제주특별자치도 제주시 한림읍 금능남로 127,의료관광,국내외 고객 및 환자를 대상으로 최고의 안티에이징 의료서비스와 성형 및 메디컬스킨케...,33.376056,126.244127,NaN,...,제주시,region>region1,13.0,한림,region1>13,썬플라워의원,2.019023e+12,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,2562.0

In [9]:
rating_file.columns

Index(['alltag', 'contentsid', 'title', 'address', 'roadaddress', 'tag',
       'introduction', 'latitude', 'longitude', 'postcode', 'phoneno',
       'contentscd.value', 'contentscd.label', 'contentscd.refId',
       'region1cd.value', 'region1cd.label', 'region1cd.refId',
       'region2cd.value', 'region2cd.label', 'region2cd.refId',
       'repPhoto.descseo', 'repPhoto.photoid.photoid',
       'repPhoto.photoid.imgpath', 'repPhoto.photoid.thumbnailpath', '인기점수'],
      dtype='object')

In [10]:
sort_test = rating_file.sort_values(by=['contentscd.label','인기점수'],ascending=[True,False],inplace=False)

In [11]:
sort_test.loc[:,['title','contentscd.label','인기점수']]

                     title contentscd.label       인기점수
4162                 사려니숲길              관광지  1276524.0
4074            우도(해양도립공원)              관광지  1188600.0
4259  성산일출봉(UNESCO 세계자연유산)              관광지  1027366.0
4243                   비자림              관광지   916549.0
3896                 천지연폭포              관광지   645261.0
...                    ...              ...        ...
2792                   의식주             테마여행       74.0
1557                    민속             테마여행       60.0
94                     삼다도             테마여행       54.0
1523                제주의 역사             테마여행       54.0
1855                  지형지질             테마여행       42.0

[4270 rows x 3 columns]

In [12]:
kkkk = set(sort_test['contentscd.label'])
kkkk

{'관광지', '미등록 콘텐츠', '쇼핑', '숙박', '음식점', '정보', '축제/행사', '테마여행'}

In [13]:
attraction_list = sort_test[sort_test['contentscd.label']=='관광지']
shopping_list = sort_test[sort_test['contentscd.label']=='쇼핑']
accomodation_list = sort_test[sort_test['contentscd.label']=='숙박']
restaurant_list = sort_test[sort_test['contentscd.label']=='음식점']

# 관광지 유형별로 구분한 DataFrame 확인

In [14]:
attraction_list.loc[:,['title','인기점수']]

                     title       인기점수
4162                 사려니숲길  1276524.0
4074            우도(해양도립공원)  1188600.0
4259  성산일출봉(UNESCO 세계자연유산)  1027366.0
4243                   비자림   916549.0
3896                 천지연폭포   645261.0
...                    ...        ...
3683             영등할망 신화공원      411.0
2033            헌마공신김만일기념관      287.0
3751              훈데르트바서파크      166.0
2546                 세화소품관       60.0
3779             무비랜드왁스뮤지엄        NaN

[1093 rows x 2 columns]

In [15]:
shopping_list.loc[:,['title','인기점수']]

                   title      인기점수
3686              동문재래시장  175199.0
3875           서귀포매일올레시장  125774.0
3259  제주관광공사 중문면세점 (내국인)  121459.0
4189            제주민속오일시장   95465.0
3295                 벨롱장   49121.0
...                  ...       ...
1148             동문시장(주)     784.0
2281           제주 중앙지하상가     686.0
2392              화북종합시장     450.0
723                 소소한담     434.0
629           하나로마트 서귀포점      18.0

[127 rows x 2 columns]

In [16]:
sort_test.to_csv(dir_path+"/tourist_attraction_with_rating" + '_sort_by_type.csv',encoding='utf-8-sig')

In [17]:
sort_test.groupby('contentscd.label')['인기점수'].describe()

,count,mean,std,min,25%,50%,75%,max
contentscd.label,,,,,,,,
관광지,1092.0,30926.365385,84830.909259,60.0,4718.50,8928.5,25449.25,1276524.0
미등록 콘텐츠,1.0,13606.000000,NaN,13606.0,13606.00,13606.0,13606.00,13606.0
쇼핑,127.0,11249.212598,23624.782562,18.0,2433.00,5227.0,8744.50,175199.0
숙박,922.0,4688.940347,6564.685102,283.0,2168.50,3063.0,4786.25,97453.0
음식점,1614.0,5024.000620,9624.975014,2.0,1112.00,2789.5,5130.00,144324.0
정보,2.0,366.000000,149.906638,260.0,313.00,366.0,419.00,472.0
축제/행사,98.0,21258.846939,35761.102251,8.0,3021.75,9368.5,23492.25,244000.0
테마여행,404.0,19752.438119,24204.255924,42.0,4460.25,10522.0,24360.50,133691.0

In [18]:
attraction_list_describe_tags = attraction_list['tag'].str.get_dummies(sep=',')

In [19]:
attraction_list_describe_tags.describe()

,해변,#예술 #경관/포토,4.3,6차산업,ATV,waterleisure,가을,가족,가족여행,가죽공방,...,환상자전거도로,효돈천,휴식,휴식/치유,휴식/힐링,휴양림,흐림,흑돼지,흑염소,힐링
count,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,...,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.00000,1093.000000,1093.000000,1093.000000
mean,0.000915,0.000915,0.040256,0.002745,0.001830,0.004575,0.114364,0.002745,0.000915,0.001830,...,0.000915,0.000915,0.006404,0.029277,0.127173,0.003660,0.10979,0.000915,0.000915,0.007319
std,0.030248,0.030248,0.196649,0.052342,0.042757,0.067512,0.318399,0.052342,0.030248,0.042757,...,0.030248,0.030248,0.079807,0.168660,0.333319,0.060412,0.31277,0.030248,0.030248,0.085278
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000

In [20]:
attraction_list_describe_tags

,해변,#예술 #경관/포토,4.3,6차산업,ATV,waterleisure,가을,가족,가족여행,가죽공방,...,환상자전거도로,효돈천,휴식,휴식/치유,휴식/힐링,휴양림,흐림,흑돼지,흑염소,힐링
4162,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4074,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4259,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3896,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3683,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2033,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3751,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2546,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3779,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
checking_tags = attraction_list_describe_tags.describe()
checking_tags

,해변,#예술 #경관/포토,4.3,6차산업,ATV,waterleisure,가을,가족,가족여행,가죽공방,...,환상자전거도로,효돈천,휴식,휴식/치유,휴식/힐링,휴양림,흐림,흑돼지,흑염소,힐링
count,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,...,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.000000,1093.00000,1093.000000,1093.000000,1093.000000
mean,0.000915,0.000915,0.040256,0.002745,0.001830,0.004575,0.114364,0.002745,0.000915,0.001830,...,0.000915,0.000915,0.006404,0.029277,0.127173,0.003660,0.10979,0.000915,0.000915,0.007319
std,0.030248,0.030248,0.196649,0.052342,0.042757,0.067512,0.318399,0.052342,0.030248,0.042757,...,0.030248,0.030248,0.079807,0.168660,0.333319,0.060412,0.31277,0.030248,0.030248,0.085278
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000

In [22]:
checking_tags = checking_tags.iloc[1]
checking_tags

 해변            0.000915
#예술  #경관/포토    0.000915
4.3            0.040256
6차산업           0.002745
ATV            0.001830
                 ...
휴양림            0.003660
흐림             0.109790
흑돼지            0.000915
흑염소            0.000915
힐링             0.007319
Name: mean, Length: 347, dtype: float64

In [23]:
type(checking_tags)

pandas.core.series.Series

In [24]:
checking_tags.reset_index()

           index      mean
0             해변  0.000915
1    #예술  #경관/포토  0.000915
2            4.3  0.040256
3           6차산업  0.002745
4            ATV  0.001830
..           ...       ...
342          휴양림  0.003660
343           흐림  0.109790
344          흑돼지  0.000915
345          흑염소  0.000915
346           힐링  0.007319

[347 rows x 2 columns]

In [25]:
tmp_tag_checking = checking_tags.to_frame()
tmp_tag_checking

                 mean
 해변          0.000915
#예술  #경관/포토  0.000915
4.3          0.040256
6차산업         0.002745
ATV          0.001830
...               ...
휴양림          0.003660
흐림           0.109790
흑돼지          0.000915
흑염소          0.000915
힐링           0.007319

[347 rows x 1 columns]

In [26]:
tmp_tag_checking.sort_values(by='mean',ascending=False,inplace=True)
tmp_tag_checking

           mean
어트랙션   0.509607
자연경관   0.447392
커플     0.337603
맑음     0.334858
친구     0.310156
...         ...
수영장    0.000915
수월봉    0.000915
수제캔디   0.000915
쉼터     0.000915
신석기시대  0.000915

[347 rows x 1 columns]

In [31]:
attraction_tag = tmp_tag_checking.iloc[50:100]
attraction_tag

                  mean
우수관광사업체       0.022873
봄꽃            0.022873
중/장년          0.022873
해수욕장          0.021958
숲             0.021043
밤             0.020128
예술            0.020128
단풍            0.018298
캠핑            0.017383
캠핑장           0.016468
승마            0.016468
한라산           0.015554
숲길            0.015554
유네스코          0.015554
계곡            0.014639
안전여행스탬프       0.013724
골프            0.013724
유채꽃           0.013724
수국            0.013724
의료관광          0.012809
야영장           0.012809
미술관           0.011894
노년            0.011894
산             0.010979
벚꽃            0.010064
웰니스           0.010064
동백            0.010064
동굴            0.010064
섬속의섬          0.010064
전시와 행사        0.009149
걷기            0.009149
곶자왈           0.009149
폭포            0.008234
등대            0.008234
낚시            0.008234
제주명품42        0.008234
카페            0.007319
힐링            0.007319
스파            0.007319
억새            0.006404
녹차            0.006404
호텔            0.006404
휴식            0.006404
어린이동물농장       0.005489
매화            0.005489
감귤            0.005489
용천수           0.005489
원데이클래스        0.005489
waterleisure  0.004575
제주7대도로        0.004575

#무분별한 태그 남용으로 인한 빈도수 기반으로 상위 태그 추출 - 관광지

In [41]:
attraction_tag_list = list(attraction_tag.index)
attraction_tag_list

['어트랙션',
 '자연경관',
 '커플',
 '맑음',
 '친구',
 '체험',
 '아이',
 '어린이',
 '문화관광',
 '도보',
 '도보여행',
 '포토스팟',
 '경관/포토',
 '역사유적',
 '혼자',
 '문화유적지',
 '걷기/등산',
 '부모',
 '레저/체험',
 '실내관광지',
 '액티비티',
 '해변',
 '오름',
 '휴식/힐링',
 '가을',
 '흐림',
 '사계절',
 '여름',
 '봄']

In [43]:
attraction_list['tag']

4162                숲길,걷기/등산,친구,커플,흐림,봄,자연경관,도보여행,도보,숲,단풍
4074           섬속의섬,경관/포토,아이,맑음,자연경관,포토스팟,어린이,봄꽃,유채꽃,유네스코
4259                        일출,오름,경관/포토,부모,자연경관,포토스팟,유네스코
4243                        걷기/등산,아이,흐림,여름,힐링,자연경관,어린이,수국
3896                   폭포,밤,경관/포토,부모,맑음,여름,자연경관,포토스팟,유네스코
                              ...
3683                      테마공원,경관/포토,문화유적지,역사유적,포토스팟,어트랙션
2033    커플,부모,혼자,친구,아이,맑음,흐림,비.눈,경관/포토,휴식/힐링,미술/박물관,사계...
3751                                문화관광,건축문화기행,테마공원,포토스팟
2546                                      기념품,소품,잡화,선물,음식
3779                                       박물관,밀랍인형,실내관광지
Name: tag, Length: 1093, dtype: object

In [ ]:
#list(set(a) & set(b))

##error point를 찾기 위한 코드

In [44]:
for tag_list in attraction_list['tag']:
  if type(tag_list) == float:
    print(tag_list)
    break

##관광지 tag가 비어있는지 확인

In [45]:
attraction_list['tag'].isnull().sum()

0

##String의 나열에서 list로 태그를 바꿔주기

In [50]:
attraction_list['tag'] = attraction_list['tag'].apply(lambda x: x.split(','))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [51]:
attraction_list['tag']

4162    [숲길, 걷기/등산, 친구, 커플, 흐림, 봄, 자연경관, 도보여행, 도보, 숲, 단풍]
4074    [섬속의섬, 경관/포토, 아이, 맑음, 자연경관, 포토스팟, 어린이, 봄꽃, 유채꽃...
4259                [일출, 오름, 경관/포토, 부모, 자연경관, 포토스팟, 유네스코]
4243               [걷기/등산, 아이, 흐림, 여름, 힐링, 자연경관, 어린이, 수국]
3896         [폭포, 밤, 경관/포토, 부모, 맑음, 여름, 자연경관, 포토스팟, 유네스코]
                              ...
3683               [테마공원, 경관/포토, 문화유적지, 역사유적, 포토스팟, 어트랙션]
2033    [커플, 부모, 혼자, 친구, 아이, 맑음, 흐림, 비.눈, 경관/포토, 휴식/힐링...
3751                           [문화관광, 건축문화기행, 테마공원, 포토스팟]
2546                                [기념품, 소품, 잡화, 선물, 음식]
3779                                   [박물관, 밀랍인형, 실내관광지]
Name: tag, Length: 1093, dtype: object

In [57]:
attraction_list['tag'] = attraction_list['tag'].apply(lambda x: list(set(x)&set(attraction_tag_list)))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [58]:
attraction_list['tag']

4162               [자연경관, 친구, 도보여행, 도보, 커플, 봄, 흐림, 걷기/등산]
4074                     [자연경관, 포토스팟, 아이, 어린이, 맑음, 경관/포토]
4259                          [부모, 자연경관, 포토스팟, 경관/포토, 오름]
4243                       [자연경관, 아이, 어린이, 여름, 흐림, 걷기/등산]
3896                      [부모, 자연경관, 포토스팟, 여름, 맑음, 경관/포토]
                              ...
3683                     [포토스팟, 역사유적, 어트랙션, 경관/포토, 문화유적지]
2033    [부모, 포토스팟, 실내관광지, 역사유적, 친구, 아이, 휴식/힐링, 어린이, 커플...
3751                                         [문화관광, 포토스팟]
2546                                                   []
3779                                              [실내관광지]
Name: tag, Length: 1093, dtype: object

In [59]:
attraction_list.loc[:,['title','인기점수','contentscd.label','tag']]

,title,인기점수,contentscd.label,tag
4162,사려니숲길,1276524.0,관광지,"[자연경관, 친구, 도보여행, 도보, 커플, 봄, 흐림, 걷기/등산]"
4074,우도(해양도립공원),1188600.0,관광지,"[자연경관, 포토스팟, 아이, 어린이, 맑음, 경관/포토]"
4259,성산일출봉(UNESCO 세계자연유산),1027366.0,관광지,"[부모, 자연경관, 포토스팟, 경관/포토, 오름]"
4243,비자림,916549.0,관광지,"[자연경관, 아이, 어린이, 여름, 흐림, 걷기/등산]"
3896,천지연폭포,645261.0,관광지,"[부모, 자연경관, 포토스팟, 여름, 맑음, 경관/포토]"
...,...,...,...,...
3683,영등할망 신화공원,411.0,관광지,"[포토스팟, 역사유적, 어트랙션, 경관/포토, 문화유적지]"
2033,헌마공신김만일기념관,287.0,관광지,"[부모, 포토스팟, 실내관광지, 역사유적, 친구, 아이, 휴식/힐링, 어린이, 커플..."
3751,훈데르트바서파크,166.0,관광지,"[문화관광, 포토스팟]"
2546,세화소품관,60.0,관광지,[]
3779,무비랜드왁스뮤지엄,NaN,관광지,[실내관광지]

In [60]:
attraction_list.reset_index(drop=True,inplace=True)
attraction_list.loc[:,['title','인기점수','contentscd.label','tag']]

,title,인기점수,contentscd.label,tag
0,사려니숲길,1276524.0,관광지,"[자연경관, 친구, 도보여행, 도보, 커플, 봄, 흐림, 걷기/등산]"
1,우도(해양도립공원),1188600.0,관광지,"[자연경관, 포토스팟, 아이, 어린이, 맑음, 경관/포토]"
2,성산일출봉(UNESCO 세계자연유산),1027366.0,관광지,"[부모, 자연경관, 포토스팟, 경관/포토, 오름]"
3,비자림,916549.0,관광지,"[자연경관, 아이, 어린이, 여름, 흐림, 걷기/등산]"
4,천지연폭포,645261.0,관광지,"[부모, 자연경관, 포토스팟, 여름, 맑음, 경관/포토]"
...,...,...,...,...
1088,영등할망 신화공원,411.0,관광지,"[포토스팟, 역사유적, 어트랙션, 경관/포토, 문화유적지]"
1089,헌마공신김만일기념관,287.0,관광지,"[부모, 포토스팟, 실내관광지, 역사유적, 친구, 아이, 휴식/힐링, 어린이, 커플..."
1090,훈데르트바서파크,166.0,관광지,"[문화관광, 포토스팟]"
1091,세화소품관,60.0,관광지,[]
1092,무비랜드왁스뮤지엄,NaN,관광지,[실내관광지]

In [63]:
attraction_list['인기점수'].fillna(value=0,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [64]:
attraction_list.loc[:,['title','인기점수','contentscd.label','tag']]

,title,인기점수,contentscd.label,tag
0,사려니숲길,1276524.0,관광지,"[자연경관, 친구, 도보여행, 도보, 커플, 봄, 흐림, 걷기/등산]"
1,우도(해양도립공원),1188600.0,관광지,"[자연경관, 포토스팟, 아이, 어린이, 맑음, 경관/포토]"
2,성산일출봉(UNESCO 세계자연유산),1027366.0,관광지,"[부모, 자연경관, 포토스팟, 경관/포토, 오름]"
3,비자림,916549.0,관광지,"[자연경관, 아이, 어린이, 여름, 흐림, 걷기/등산]"
4,천지연폭포,645261.0,관광지,"[부모, 자연경관, 포토스팟, 여름, 맑음, 경관/포토]"
...,...,...,...,...
1088,영등할망 신화공원,411.0,관광지,"[포토스팟, 역사유적, 어트랙션, 경관/포토, 문화유적지]"
1089,헌마공신김만일기념관,287.0,관광지,"[부모, 포토스팟, 실내관광지, 역사유적, 친구, 아이, 휴식/힐링, 어린이, 커플..."
1090,훈데르트바서파크,166.0,관광지,"[문화관광, 포토스팟]"
1091,세화소품관,60.0,관광지,[]
1092,무비랜드왁스뮤지엄,0.0,관광지,[실내관광지]

In [65]:
attraction_list['tag'] = attraction_list['tag'].apply(lambda x: ','.join(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [66]:
attraction_list['tag'].sample()

167    실내관광지,액티비티,어린이,레저/체험,어트랙션,체험
Name: tag, dtype: object

In [67]:
attraction_list.to_csv(dir_path+'/attraction_list_top30_tags.csv',)

#쇼핑, 숙박, 식당도 상위 N개의 대표적인 태그만 적용하기

In [73]:
shopping_list.sample()

,alltag,contentsid,title,address,roadaddress,tag,introduction,latitude,longitude,postcode,...,region1cd.label,region1cd.refId,region2cd.value,region2cd.label,region2cd.refId,repPhoto.descseo,repPhoto.photoid.photoid,repPhoto.photoid.imgpath,repPhoto.photoid.thumbnailpath,인기점수
4161,"전통시장,공용주차장,아주 어려움",CONT_000000000500759,한림민속오일시장,제주특별자치도 제주시 한림읍 대림리 1698-4,제주특별자치도 제주시 한림읍 한수풀로4길 10,"전통시장,쇼핑,상점/상가,오일장,관광기념품",여러분 곁에 가까이 있는 한림조끄뜨레시장,33.420152,126.274234,63026,...,제주시,region>region1,13.0,한림,region1>13,Hallim Minsok 5-day Market,20698.0,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,23922.0

In [74]:
shopping_list['tag']

3686              쇼핑,전통시장,기념품,밤,상점/상가,관광기념품
3875            쇼핑,전통시장,기념품,상점/상가,오일장,관광기념품
3259    쇼핑,면세점,기념품,관광기념품,상점/상가,dutyfreeshop
4189                쇼핑,전통시장,오일장,상점/상가,관광기념품
3295                쇼핑,플리마켓,기념품,관광기념품,상점/상가
                       ...
1148                    전통시장,쇼핑,상점/상가,관광기념품
2281                    전통시장,상점/상가,쇼핑,관광기념품
2392                    전통시장,쇼핑,상점/상가,관광기념품
723                          쇼핑,관광기념품,상점/상가
629                       하나로마트,서귀포시내,음식,식당
Name: tag, Length: 127, dtype: object

In [77]:
shopping_dummy = shopping_list['tag'].str.get_dummies(sep=',')
restaurant_dummy = restaurant_list['tag'].str.get_dummies(sep=',')
accomodation_dummy = accomodation_list['tag'].str.get_dummies(sep=',')

In [90]:
shopping_tag_list = shopping_dummy.describe().iloc[1]
restaurant_tag_list = restaurant_dummy.describe().iloc[1]
accomodation_tag_list = accomodation_dummy.describe().iloc[1]

In [91]:
restaurant_tag_list

24시          0.000616
24시간식당       0.000616
24시운영        0.000616
24시음식점       0.000616
3657하우스피자    0.000616
               ...
흑우           0.000616
흑차           0.000616
흑한우          0.000616
히레까스         0.000616
힐링           0.001232
Name: mean, Length: 2176, dtype: float64

In [96]:
shopping_tag_list = shopping_tag_list.to_frame()
restaurant_tag_list = restaurant_tag_list.to_frame()
accomodation_tag_list = accomodation_tag_list.to_frame()

In [98]:
restaurant_tag_list.reset_index(inplace=True)
restaurant_tag_list

          index      mean
0           24시  0.000616
1        24시간식당  0.000616
2         24시운영  0.000616
3        24시음식점  0.000616
4     3657하우스피자  0.000616
...         ...       ...
2171         흑우  0.000616
2172         흑차  0.000616
2173        흑한우  0.000616
2174       히레까스  0.000616
2175         힐링  0.001232

[2176 rows x 2 columns]

In [101]:
restaurant_tag_list = restaurant_tag_list.rename(columns = {'index':'tag'})
shopping_tag_list = shopping_tag_list.rename(columns = {'index':'tag'})
accomodation_tag_list = accomodation_tag_list.rename(columns = {'index':'tag'})

In [104]:
restaurant_tag_list.sort_values(by = 'mean',ascending=False).head(50)

         tag      mean
1411      음식  0.990142
1753      카페  0.244609
1118      식당  0.212569
1155   아메리카노  0.154036
1768      커피  0.138632
1962      한식  0.129390
2127     흑돼지  0.094270
1754    카페라떼  0.090573
448      디저트  0.088725
54      갈치조림  0.074553
837        빵  0.073937
2102       회  0.065927
1410      음료  0.055453
1235     에이드  0.054221
1266     오겹살  0.052988
212     김치찌개  0.049291
1873     파스타  0.049291
1518  제주갈치조림  0.048675
2133   흑돼지구이  0.047443
2034     해산물  0.046827
689    바닐라라떼  0.046827
48      갈치구이  0.045595
114    고등어구이  0.044978
1479     전복죽  0.044362
2114      횟집  0.044362
2052    향토음식  0.043130
1305    옥돔구이  0.041898
729     베이커리  0.041282
116    고등어조림  0.036352
897     샌드위치  0.036352
1465   전복뚝배기  0.035736
805      브런치  0.035736
664       물회  0.035736
1459      전복  0.035120
1234   에스프레소  0.034504
1928      피자  0.033272
1976      한치  0.033272
961    성게미역국  0.032656
1776     케이크  0.032039
1505      정식  0.032039
1517  제주갈치구이  0.032039
107     고기국수  0.032039
418     돼지구이  0.030807
118     고등어회  0.030191
485       라면  0.029575
1760     칼국수  0.028959
866      삼겹살  0.028959
1755    카페모카  0.028959
372      돈까스  0.028959
774      볶음밥  0.028343

In [106]:
accomodation_tag_list.sort_values(by = 'mean',ascending=False).head(50)

             mean
숙소       0.889371
공공와이파이존  0.603037
펜션       0.478308
휴양펜션     0.451193
주차장      0.376356
바비큐      0.351410
휴식       0.267896
해수욕장     0.261388
민박       0.248373
자연경관     0.239696
독채       0.214751
가족       0.190889
게스트하우스   0.184382
호텔       0.175705
해변       0.175705
온돌방      0.172451
단체여행객    0.168113
수영장      0.136659
농어촌민박    0.123644
조식 포함    0.120390
조식       0.098698
관광호텔     0.091106
체험       0.085683
리조트      0.084599
교통       0.077007
양식레스토랑   0.072668
정원       0.072668
수상레저     0.071584
카페       0.061822
주방기구     0.059653
휴양콘도     0.059653
힐링       0.057484
공항       0.056399
안전인증민박   0.054230
힐링쉼터     0.053145
가족호텔     0.046638
고향민박     0.044469
해안도로     0.043384
추자도      0.039046
물품보관서비스  0.037961
서귀포      0.036876
스파       0.035792
편의시설     0.035792
식당       0.032538
돌담길      0.028200
비즈니스센터   0.028200
반려동물보호소  0.027115
안전인증숙소   0.027115
음식       0.027115
산책로      0.027115